version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Adafruit
  - ALARMHR
  - ALARMWDAYS
  - CLKOE
  - CLKOUT
  - decodewday
  - doxyfile
  - DSALARM
  - EEPROM
  - EnviroDIY
  - INTB
  - INTCN
  - INTRB
  - MAXRTC
  - MBED
  - mcss
  - PCFALARM
  - PINALARM
  - RTClib
  - Sparkfun
  - SREGADDR
  - Stoffregen
  - testall
  - VBATEN
  - wdaybase
  - wdayfirst
ignoreWords: []
import: []
